version: "3.7"

services:
  db:
    image: mysql:8.0.24
    restart: always
    environment:
      MYSQL_DATABASE: juding
      MYSQL_ROOT_PASSWORD: judingPassword_DAWG2
  web:
    image: daw2021webapp2/juding:v1.2
    restart: always
    ports:
      - "8443:8443"
    links:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db/juding
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: judingPassword_DAWG2
